exclude:
  languages

mapping:
  "Stefan Heimes <stefan_heimes@hotmail.com>":
    - "Stefan heimes <stefan_heimes@hotmail.com>"
    - "chibineko <stefan_heimes@hotmail.com>"
    - "stefanheimes <stefan_heimes@hotmail.com>"
    - "Stefan Heimes <cms@men-at-work.de>"
  "Christopher Boelter <christopher@boelter.eu>":
    - "cogizz <c.boelter@cogizz.de>"
    - "cboelter <christopher@boelter.eu>"
    - "Christopher Boelter <c.boelter@cogizz.de>"
  "Patrick Kahl <kahl.patrick@googlemail.com>": "patrickkahl (Patrick Kahl) <Kahl.Patrick@googlemail.com>"
  "Andreas Nölke <zero@brothers-project.de>":
    - "Zeromax <zero@brothers-project.de>"
    - "Zeromax <zero@prothers-project.de>"
  "David Molineus <david.molineus@netzmacht.de>":
    - "netzmacht <mail@netzmacht.de>"
    - "David Molineus <mail@netzmacht.de>"
  "Alexander Menk <a.menk@imi.de>":
    - "Alexander Menk <alex.menk@gmail.com>"
  "Ingolf Steinhardt <info@e-spin.de>":
    - "xantippe <info@e-spin.de>"
    - "zonky2 <info@e-spin.de>"
  "Cliff Parnitzky <contao@cliff-parnitzky.de>":
    - "cliffparnitzky <contao@cliff-parnitzky.de>"
